services:
  tocloud-db:
    image: postgres:16
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  tocloud:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - tocloud-db