# Generated by Django 4.2.6 on 2023-10-28 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=1024)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='Nome do projeto')),
                ('software_objective', models.TextField(verbose_name='Descrição do objetivo do software (gestão de projetos)')),
                ('features_and_functionality', models.TextField(verbose_name='Principais recursos e funcionalidades esperadas')),
                ('target_audience', models.CharField(max_length=200, verbose_name='Público-alvo ou segmento de mercado')),
                ('technical_requirements', models.TextField(verbose_name='Requisitos técnicos específicos (por exemplo, Python, Django, banco de dados, etc.)')),
                ('target_platforms', models.CharField(max_length=100, verbose_name='Plataformas alvo (web, dispositivos móveis, etc.)')),
                ('design_guidelines', models.TextField(verbose_name='Diretrizes de design e estilo desejadas')),
                ('initial_design_ideas', models.TextField(verbose_name='Esboços ou ideias de design iniciais (se disponíveis)')),
                ('security_requirements', models.TextField(verbose_name='Necessidades de segurança (autenticação, autorização, criptografia, etc.)')),
                ('initial_scope', models.TextField(verbose_name='Escopo inicial do projeto')),
                ('future_scope', models.TextField(verbose_name='Recursos que podem ser adicionados em fases posteriores')),
                ('start_date', models.DateField(verbose_name='Data de início estimada')),
                ('desired_completion_date', models.DateField(verbose_name='Prazo de conclusão desejado')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Orçamento disponível')),
                ('additional_notes', models.TextField(verbose_name='Quaisquer informações adicionais que a equipe de desenvolvimento deve saber')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.team', verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
