# Generated by Django 4.2.6 on 2023-10-28 13:29

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_desired_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.CharField(verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team', verbose_name='Time'),
        ),
    ]
