# Generated by Django 4.2.6 on 2023-10-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_projecttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='task_done',
            field=models.BooleanField(default=False),
        ),
    ]
