# Generated by Django 4.2.6 on 2023-10-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_projecttask_task_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='design_guidelines',
        ),
        migrations.RemoveField(
            model_name='project',
            name='initial_design_ideas',
        ),
        migrations.RemoveField(
            model_name='project',
            name='security_requirements',
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.TextField(null=True, verbose_name='Tarefas'),
        ),
    ]
