# Generated by Django 4.2.6 on 2023-10-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_project_design_guidelines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome do projeto'),
        ),
    ]
