# Generated by Django 4.2.6 on 2023-10-29 16:44

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userinformation_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='author',
            field=models.CharField(default='admin', verbose_name=django.contrib.auth.models.User),
        ),
    ]
