# Generated by Django 4.2.6 on 2023-10-30 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_team_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_name', models.CharField()),
                ('subtask_done', models.BooleanField(default=False)),
                ('subtask_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projecttask')),
            ],
        ),
    ]
